# Generated by Django 4.0.6 on 2022-07-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
