# Generated by Django 4.0.6 on 2022-07-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_producto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Disponibilidad',
            new_name='disponibilidad',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
    ]
