# Generated by Django 4.0.6 on 2022-07-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea_pedidos',
            old_name='pedido_is',
            new_name='pedidos',
        ),
        migrations.RenameField(
            model_name='linea_pedidos',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
